name: CI
on:
  - push
  - pull_request

# Cancel running jobs for the same branch or PR
concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  build-all-devices:
    name: "Build: ${{ matrix.device }}"
    needs: generate-devices-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        device:
          - libreComputer-amlS805xAc
          - libreComputer-rocRk3399Pc
          - libreComputer-rocRk3399PcMezzanine
          - odroid-C2
          - odroid-C4
          - odroid-N2
          - olimex-teresI
          - orangePi-pc
          - orangePi-zeroPlus2H5
          - pine64-pineA64
          - pine64-pineA64LTS
          - pine64-pinebookA64
          - pine64-pinebookPro
          - pine64-pinephoneA64
          - pine64-pinephonePro
          - pine64-rockpro64
          - radxa-RockPi4
          - radxa-RockPi4C
          - radxa-zero2
          - raspberryPi-aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build archive
        run: |
          nix-build \
            -A ${{ matrix.device }}.build.archive
      - name: Rename archive
        run: |
          archive=$(readlink -f result)
          cp --dereference "$archive" "${archive#*-}"
      - name: Upload archive to Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: '*.tar.xz'
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    needs: build-all-devices
    runs-on: ubuntu-22.04
    steps:
      - name: Download archives from Artifacts
        uses: actions/download-artifact@v3
      - name: Generate _checksums.txt
        run: shasum -a 256 * | sort --key 2 --stable > _checksums.txt
        working-directory: artifact
      - name: Upload archives to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
